# auto-generated by CC_DecisionNode_OVS service
# Short python to implement Trigger.
# The following three items are important:
# 1. You must write the process_data(self) function
# 2. Read the input (from the Monitor) by calling self.read_input_line()
# 3. Call the self.active_conn method with the cc node number as a parameter.
# The following is a sample that reads time information from the Monitor and 
# will swap between nodes every 15 seconds

import time
#Required import
from Trigger.trigger import Trigger

#Required class name that inherits Trigger
class MyTrigger(Trigger):  
    
    #Required function
    def process_data(self):
        #get the cc_node numbers
        nodes = self.get_cc_node_numbers()
        self.set_active_conn("eth0", disable_others=True)
        self.set_active_conn("eth2", disable_others=False)
        #use a counter to trigger call to swap
        count = 1
        #forever loop to process data
        while True:
####Modify to process Monitor's data and Trigger a switch####
            # read a line of input (from Monitor's stdout)
            data = self.read_input_line()
            print("READ: " + str(data))
            #if data yet exists, restart loop
            if data == None:
                continue
            # assuming we get one update per second
            count = count + 1
            new_time = int(data)
            #set active node every 30 seconds
            if count == 30:
                self.set_active_conn("eth0", disable_others=True)
                self.set_active_conn("eth1", disable_others=False)
            if count == 60:
                self.set_active_conn("eth0", disable_others=True)
                self.set_active_conn("eth3", disable_others=False)
            if count == 90:
                self.set_active_conn("eth0", disable_others=True)
                self.set_active_conn("eth2", disable_others=False)
                count = 1
####